import { useState, useRef, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { Filter } from 'lucide-react';

// TrackingView's table is 28 columns wide and can be 70+ vh tall, wrapped
// in a `.table-wrap` with overflow:auto on both axes. A dropdown panel
// nested inside a `th` (position: sticky, itself inside that scrolling
// container) gets CLIPPED by the container's own overflow boundary
// whenever the column sits near the right edge or bottom of the current
// scroll position — for a header far enough over, the "Tətbiq et" button
// ends up outside the visible/clickable region entirely, so the click
// either does nothing or lands on whatever's underneath. That silently
// swallowed apply click was the real cause of "some columns' filters
// don't seem to save" — the filter was never actually applied in the
// first place, not a localStorage bug. Rendering the dropdown through a
// portal straight to document.body, positioned with `position: fixed`
// from the trigger button's own bounding rect, escapes that clipping
// entirely regardless of which column or how far the table is scrolled.
export default function ColumnFilterHeader({ label, values, selected, onChange, onSort, sortIndicator, sticky, headerStyle }) {
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState('');
  const [draft, setDraft] = useState(selected);
  const [pos, setPos] = useState(null);
  const triggerRef = useRef(null);
  const panelRef = useRef(null);
  // Mirrors `open` for the mount-once listeners below, which close over
  // this ref instead of the `open` state directly — re-attaching a native
  // 'mousedown' listener every time `open` flips true (i.e. depending on
  // `[open]`) raced with the very click that set it true, immediately
  // closing the panel it had just opened. A single listener attached once
  // on mount, reading the latest open/ref state through refs, sidesteps
  // that entirely.
  const openRef = useRef(open);
  openRef.current = open;

  useEffect(() => {
    if (open) setDraft(new Set(selected));
  }, [open, selected]);

  function openPanel() {
    const r = triggerRef.current?.getBoundingClientRect();
    if (r) setPos({ top: r.bottom + 4, left: r.left });
    setOpen(true);
  }

  useEffect(() => {
    function onClickOutside(e) {
      if (!openRef.current) return;
      if (
        (!triggerRef.current || !triggerRef.current.contains(e.target)) &&
        (!panelRef.current || !panelRef.current.contains(e.target))
      ) {
        setOpen(false);
      }
    }
    // Deliberately NOT closing on scroll/resize: the panel is `position:
    // fixed` from a one-time-computed viewport rect, so a later scroll can
    // leave it visually detached from its column — a minor cosmetic
    // tradeoff, but closing on scroll also fires from the scroll events
    // generated by opening the panel itself (the browser bringing the
    // trigger button into view as part of the click that opens it),
    // closing the panel before a user can ever interact with it.
    document.addEventListener('mousedown', onClickOutside);
    return () => document.removeEventListener('mousedown', onClickOutside);
  }, []);

  const isFiltered = selected && selected.size > 0 && selected.size < values.length;
  const filteredValues = values.filter((v) => v.toLowerCase().includes(search.toLowerCase()));

  function toggleValue(v) {
    setDraft((prev) => {
      const next = new Set(prev);
      if (next.has(v)) next.delete(v); else next.add(v);
      return next;
    });
  }
  function selectAll() { setDraft(new Set(values)); }
  function selectNone() { setDraft(new Set()); }
  function apply() { onChange(draft); setOpen(false); }
  function cancel() { setOpen(false); }

  return (
    <th style={{ position: 'sticky', top: 0, ...headerStyle }} className={sticky ? 'sticky-col' : undefined}>
      <div ref={triggerRef} style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
        <span onClick={(e) => onSort && onSort(e)} style={{ cursor: onSort ? 'pointer' : undefined, display: 'flex', alignItems: 'center', gap: 3 }}>
          {label} {sortIndicator}
        </span>
        <button
          onClick={() => (open ? setOpen(false) : openPanel())}
          style={{ display: 'flex', border: 'none', background: 'none', cursor: 'pointer', padding: '2px', color: isFiltered ? 'var(--blue)' : 'var(--ink-400)', lineHeight: 1 }}
          title="Filtrlə"
        >
          <Filter size={12} strokeWidth={2.3} fill={isFiltered ? 'currentColor' : 'none'} />
        </button>
      </div>
      {open && pos && createPortal(
        <div ref={panelRef} style={{
          position: 'fixed', top: pos.top, left: pos.left, zIndex: 1000,
          background: 'var(--surface)', border: '1px solid var(--ink-300)', borderRadius: 10,
          boxShadow: 'var(--shadow-lg)', padding: 10, width: 230,
          fontWeight: 400, textTransform: 'none',
        }}>
          <input type="text" placeholder="Axtar..." value={search} onChange={(e) => setSearch(e.target.value)} style={{ marginBottom: 8, fontSize: 12.5 }} />
          <div style={{ display: 'flex', gap: 10, marginBottom: 8, fontSize: 11.5 }}>
            <button onClick={selectAll} className="btn-ghost" style={{ padding: 0 }}>Hamısını seç</button>
            <button onClick={selectNone} style={{ border: 'none', background: 'none', color: 'var(--red)', cursor: 'pointer', padding: 0, fontSize: 11.5 }}>Heç birini seçmə</button>
          </div>
          <div style={{ maxHeight: 200, overflow: 'auto', marginBottom: 10, borderTop: '1px solid var(--ink-100)', borderBottom: '1px solid var(--ink-100)', padding: '4px 0' }}>
            {filteredValues.map((v) => (
              <label key={v} style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12.5, padding: '3px 0', cursor: 'pointer' }}>
                <input type="checkbox" checked={draft.has(v)} onChange={() => toggleValue(v)} style={{ width: 'auto' }} />
                <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{v}</span>
              </label>
            ))}
            {filteredValues.length === 0 && <div style={{ fontSize: 12, color: 'var(--ink-400)', padding: '6px 0' }}>Tapılmadı</div>}
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            <button onClick={cancel} className="btn btn-outline btn-sm" style={{ flex: 1 }}>Ləğv et</button>
            <button onClick={apply} className="btn btn-primary btn-sm" style={{ flex: 1 }}>Tətbiq et</button>
          </div>
        </div>,
        document.body
      )}
    </th>
  );
}
